INSERT INTO USER (CREATED_DATE,EMAIL,FIRST_NAME,LAST_NAME) VALUES( CURRENT_TIMESTAMP,'ssuresh.saikishore@gmail.com','Suresh','Stalin');
INSERT INTO USER (CREATED_DATE,EMAIL,FIRST_NAME,LAST_NAME) VALUES( CURRENT_TIMESTAMP,'batathan@gmail.com','Barathan','suresh');
INSERT INTO USER (CREATED_DATE,EMAIL,FIRST_NAME,LAST_NAME) VALUES( CURRENT_TIMESTAMP,'kishore@gmail.com','Kishore','Suresh');
